CREATE DATABASE $MDB_NAME;
CREATE USER '$MDB_USER'@'$MDB_HOST' IDENTIFIED BY '$MDB_PASS';
GRANT ALL PRIVILEGES ON $MDB_NAME.* TO '$MDB_USER'@'$MDB_HOST';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MDB_PASS_ROOT';
